In [1]:
import numpy as np
import pandas as pd

In [20]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'lpa'])

In [21]:
df.head()

cgpa  profile_score  lpa
0     8              8    1
1     7              9    1
2     6             10    0
3     5              5    0

In [22]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [23]:
model = Sequential()

In [24]:
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

C:\Users\dell\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [25]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.get_weights()

[array([[-0.14007974, -0.30196154],
        [ 0.6579989 ,  0.7710624 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.0527301 ],
        [ 0.67690027]], dtype=float32),
 array([0.], dtype=float32)]

In [27]:
new_weights = [np.array([[0.1,0.1],
                        [0.1,0.1]],dtype=np.float32),
              np.array([0.,0.],dtype=np.float32),
              np.array([[0.1],
                      [0.1]],dtype=np.float32),
              np.array([0.],dtype=np.float32)]

In [28]:
model.set_weights(new_weights)

In [29]:
model.get_weights()


[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [30]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [31]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.2329
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2494 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3401 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1959 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2174 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2166 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3003 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2590 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2163 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1908 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2329 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2675 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2503 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2446 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2215 
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━━

In [32]:
model.get_weights()

[array([[0.1508938 , 0.1508938 ],
        [0.11883494, 0.11883494]], dtype=float32),
 array([0.01104185, 0.01104185], dtype=float32),
 array([[0.13392302],
        [0.13392302]], dtype=float32),
 array([0.01124988], dtype=float32)]